name: Release

on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      GRGIT_USER: musketyr
      GRGIT_PASS: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Semantic Version
      id: version
      uses: ncipollo/semantic-version-action@v1
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: publishToMavenLocal
        build-root-directory: testprojects/micronuat-grails-plugin
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: gitPublishPush -x groovydoc bintrayUpload -PbintrayUsername=${{ secrets.BINTRAY_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_KEY }} -Pversion=${{ steps.version.outputs.tag }} -Prelease=true --stacktrace
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse", "module": "micronaut-grails", "version": "${{ steps.version.outputs.tag }}", "property" : "micronaut.grails.version", "github" : ${{ toJson(github) }} }'
